# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e15ed9ec505a86d7d84484553f015f0b7eb099a5f477e20e567c82d542041d646a570ca515b80b13c65aa112b239abd2325b6284263591243bc82838b821443

test:
  secret_key_base: e452810b0cd4d56eb5c2808bebaf41f35133be58d14c159f67260038feb0460f8a47fcd8976ceea2ba9036167643b28b55eec8cb4e1539d6bfa19fe0f480800c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
